### ISSUE TITLE
Peer Review-ReadMe File

### ISSUE THREAD

**Issue by avenetto** [rrorman/progdata-class#2]
Peer Review of README file for Riley
----------------------------------------------------
Topic | Excellent | Satisfactory | Needs Work |
----------------------------|-----|-----|-----|
**Coding style** | :heavy_check_mark: | | |
**Coding strategy** | :heavy_check_mark: |  | |
**Presentation: graphs** | :heavy_check_mark: | |  |
**Presentation: tables** | :heavy_check_mark: |  | |
**Achievement, creativity** | :heavy_check_mark: | | |
**Ease of access** | :heavy_check_mark: | | |
Remarks:
- *I think you did such an awesome job creating this opening markdown file!! All of the code works as it should, and appears very nicely on your repository*
- *Some specific praise?- I love the inclusion of the spotify link! That was super creative and well executed*
- *Something I learned?- I learned how to include links by looking at your code!*
- *Specific constructive criticism?- The only thing I can add it possibly adding more pictures since you did yours so well!*
- *Something I know and that you, my peer, might like to know because it is relevant to something you struggled with.- I dont have anything to add here for this code example, it was excellent ! *

**Comment by rrorman** [comment]
Thank you so much!
