### ISSUE TITLE
Peer Review - Allison Perusse - Lab 03 

### ISSUE THREAD

**Issue by aeperusse** [rrorman/progdata-class#3]
----------------------------------------------------
Topic | Excellent | Satisfactory | Needs Work |
----------------------------|-----|-----|-----|
**Coding style** | :heavy_check_mark: | | |
**Coding strategy** | :heavy_check_mark: | | |
**Presentation: graphs** | :heavy_check_mark: | | |
**Presentation: tables** | :heavy_check_mark: | | |
**Achievement, creativity** | :heavy_check_mark: | | |
**Ease of access** | :heavy_check_mark: | | |
Remarks:
- *All of your plots look really good, especially the rainbow plot with the additional labels!*

**Comment by rrorman** [comment]
Thank you!
