### ISSUE TITLE
Peer Review - Lab 5A - Angelina Venetto

### ISSUE THREAD

**Issue by avenetto** [rrorman/progdata-class#4]
Peer Review of Lab 5A file 
----------------------------------------------------
Topic | Excellent | Satisfactory | Needs Work |
----------------------------|-----|-----|-----|
**Coding style** | :heavy_check_mark: | | |
**Coding strategy** | | :heavy_check_mark: | |
**Presentation: graphs** | :heavy_check_mark: | |  |
**Presentation: tables** | :heavy_check_mark: |  | |
**Achievement, creativity** | :heavy_check_mark: | | |
**Ease of access** | :heavy_check_mark: | | |
Remarks:
- *You did a good job making the data wider*
- *Some specific praise?- very concise code! *
- *Something I learned?- nice job pivoting
- *Specific constructive criticism?- double check for errors, you had a typo in your code that causes it to not run (referenced below)
- *Something I know and that you, my peer, might like to know because it is relevant to something you struggled with: Just double checking code!

This line runs as an error, typo in "lotr wider"
https://github.com/rrorman/progdata-class/blob/47527701ec38b7d129a58f5fd531eaf3e79f906c/Lab5A%20Univariate%20Pivoting.Rmd#L20

**Comment by rrorman** [comment]
Just fixed the typo, thank you!
