### ISSUE TITLE
Peer Review - Allison Perusse - Lab 4

### ISSUE THREAD

**Issue by aeperusse** [rrorman/progdata-class#5]
----------------------------------------------------
Topic | Excellent | Satisfactory | Needs Work |
----------------------------|-----|-----|-----|
**Coding style** | :heavy_check_mark: | | |
**Coding strategy** | :heavy_check_mark: | | |
**Presentation: graphs** | :heavy_check_mark: | | |
**Presentation: tables** | :heavy_check_mark: | | |
**Achievement, creativity** | :heavy_check_mark: | | |
**Ease of access** | :heavy_check_mark: | | |
Remarks:
- *Your code ran without issue and you did a good job recoding variables.*
- *Maybe give an explanation behind your code, when you feel its necessary, but good job!*

**Comment by rrorman** [comment]
Thank you! Will do.
