### ISSUE TITLE
Cassandra Richardson - Peer Review of Lab 7 for Reilly Orman

### ISSUE THREAD

**Issue by cassrichardson** [rrorman/progdata-class#6]
Cassandra Richardson - Peer Review of Lab 7 for Reilly Orman
----------------------------------------------------
Topic | Excellent | Satisfactory | Needs Work |
----------------------------|-----|-----|-----|
**Coding style** | :heavy_check_mark: | | |
**Coding strategy** | :heavy_check_mark: | | |
**Presentation: graphs** | :heavy_check_mark: | | |
**Presentation: tables** | :heavy_check_mark: | | |
**Achievement, creativity** | :heavy_check_mark:  | | |
**Ease of access** | :heavy_check_mark: | | |
Remarks:
- *Great job on lab 7! Your code linking to your repository for your first portfolio piece is simple, clear and easy to read. I was able to access your repository for your portfolio piece easily. However, I did not review anything in this repository as I do not think it is part of the peer review, and I did not want to overstep any boundaries with whatever data may be in that repository.*

**Comment by rrorman** [comment]
Thank you!
