### ISSUE TITLE
Peer Review - Sabrina Eisenberg - Lab 6 

### ISSUE THREAD

**Issue by sabeisenberg** [rrorman/progdata-class#7]
# Peer Review of Lab 6 for Reilly Orman

| Topic | Excellent | Satisfactory | Needs Work |
| ----------- | ----------- | ----------- | ----------- | 
| Coding Style | :heavy_check_mark: |  |  |
| Coding strategy |:heavy_check_mark:  |  |  |
| Presentation: graphs | |  |  |
| Presentation: tables | :heavy_check_mark: |  |  |
| Achievement, creativity | :heavy_check_mark: | |  |
| Ease of Access | :heavy_check_mark: |  |  |

- I thought your code was very clean and well-written! It was easy to read and navigate. 
- You seem to have a very good understanding of how to join tables. Good job! 
- I think most of our code is exactly the same, but I do see you used left join instead of inner join for the first question and I found that interesting 
- I think that adding verbal responses to the questions would be a good way to both demonstrate that you understand the use of what you did, and also to help you check and make sure that you are responding correctly. 
- One other thing I do is always assigning new objects to my responses so that I can double check them later!

**Comment by rrorman** [comment]
Thank you!
