### ISSUE TITLE
Peer Review of Lab 05A for Reilly - Priya SC

### ISSUE THREAD

**Issue by priyacollins** [rrorman/progdata-class#8]
Topic | Excellent | Satisfactory | Needs Work |
----------------------------|-----|-----|-----|
**Coding style** | :heavy_check_mark: | | |
**Coding strategy** | :heavy_check_mark: | | |
**Presentation: graphs** | :heavy_check_mark: | | |
**Presentation: tables** | :heavy_check_mark: | | |
**Achievement, creativity** | :heavy_check_mark: | | |
**Ease of access** | :heavy_check_mark: | | |
Remarks:
- *Great job with Lab 05A! Your code was clear and simple, and easy to understand. One suggestion would be to use comments to title sections for the exercises and/or to describe what specific code chunks are doing.*

**Comment by rrorman** [comment]
Thanks!
